### PR TITLE
Combine independent RE terms with same blocking variable

### LINKED ISSUE #203: missing rankUpdate! method for repeated blocking factor
Splitting the LHS of a single blocking factor across multiple RE groups breaks things.

```julia
julia> fit!(LinearMixedModel(@formula(Reaction ~ 1 + Days + (1|Subject) + (0+Days|Subject)), rcopy(R"sleepstudy")))
ERROR: MethodError: no method matching rankUpdate!(::LinearAlgebra.Diagonal{Float64,Array{Float64,1}}, ::LinearAlgebra.Diagonal{Float64,SparseArrays.SparseVector{Float64,Int32}}, ::Float64)
```
I think the idea was that everything with a shared blocking should be aggregated and that the zero-correlation structure should be achieved with `zerocorr!`, so these two specifications should yield identical blocking structures:

```julia
julia> describeblocks(LinearMixedModel(@formula(Reaction ~ 1 + Days + (1+Days|Subject)), rcopy(R"sleepstudy")))
1,1: UniformBlockDiagonal{Float64} (36, 36) UniformBlockDiagonal{Float64}
2,1: Array{Float64,2} (2, 36) Array{Float64,2}
2,2: Array{Float64,2} (2, 2) Array{Float64,2}
3,1: Array{Float64,2} (1, 36) Array{Float64,2}
3,2: Array{Float64,2} (1, 2) Array{Float64,2}
3,3: Array{Float64,2} (1, 1) Array{Float64,2}

julia> describeblocks(LinearMixedModel(@formula(Reaction ~ 1 + Days + (1|Subject) + (0+Days|Subject)), rcopy(R"sleepstudy")))
1,1: LinearAlgebra.Diagonal{Float64,Array{Float64,1}} (18, 18) LinearAlgebra.Diagonal{Float64,Array{Float64,1}}
2,1: LinearAlgebra.Diagonal{Float64,SparseArrays.SparseVector{Float64,Int32}} (18, 18) LinearAlgebra.Diagonal{Float64,SparseArrays.SparseVector{Float64,Int32}}
2,2: LinearAlgebra.Diagonal{Float64,Array{Float64,1}} (18, 18) LinearAlgebra.Diagonal{Float64,Array{Float64,1}}
3,1: Array{Float64,2} (2, 18) Array{Float64,2}
3,2: Array{Float64,2} (2, 18) Array{Float64,2}
3,3: Array{Float64,2} (2, 2) Array{Float64,2}
4,1: Array{Float64,2} (1, 18) Array{Float64,2}
4,2: Array{Float64,2} (1, 18) Array{Float64,2}
4,3: Array{Float64,2} (1, 2) Array{Float64,2}
```

That said, this is something to think for how we specify the LHS in random effects (#195), whether we want to use the no-intercept and implicit intercept formulations as special cases.

### PR DESCRIPTION
**Pull request by palday**
Fixes #203.

### CODE REVIEW

**Comment by palday** [comment]
Okay, I'm getting stuck when I test this on some simulated data. Using ['gendata'](https://gist.github.com/palday/0ce66d7a2c404a129430fa4a848d6518):

```julia
julia> df = gendata(100000,1000);

julia> @time mnc = zerocorr!(LMM(@formula(y ~ 1 + x + w + z + sex + group + (1 + y| ID)), df), [:ID]);
  0.839160 seconds (1.45 M allocations: 128.144 MiB, 6.70% gc time)

# for a single continuous covariate, delivers the same model as mnc
julia> @time mind = LMM(@formula(y ~ 1 + x + w + z + sex + group + (1| ID) + (0+y|ID)), df);
  1.089750 seconds (982.96 k allocations: 125.052 MiB, 4.00% gc time)

julia> @time fit!(mnc)
  0.447501 seconds (935.71 k allocations: 48.277 MiB, 41.18% gc time)
Linear mixed model fit by maximum likelihood
 y ~ 1 + x + w + z + sex + group + (1 + y | ID)
     logLik        -2 logLik          AIC             BIC       
  1.50403153×10⁶ -3.00806306×10⁶ -3.00803906×10⁶  -3.0079249×10⁶

Variance components:
            Column           Variance            Std.Dev.       Corr.
ID       (Intercept)  0.000000245883647524756 0.00049586656222
         y            0.002233402276304851178 0.04725888568624  0.00
Residual              0.000000000000002910355 0.00000005394771
 Number of obs: 100000; levels of grouping factors: 1000

  Fixed-effects parameters:
────────────────────────────────────────────────────────────
                 Estimate    Std.Error      z value  P(>|z|)
────────────────────────────────────────────────────────────
(Intercept)  -1.5368e-5    1.56808e-5   -0.980057     0.3271
x             1.67994e-14  6.22273e-10   2.69968e-5   1.0000
w             2.86739e-14  6.19481e-10   4.62869e-5   1.0000
z             4.10742e-14  6.2029e-10    6.62178e-5   0.9999
sex: m        1.75515e-14  3.84805e-10   4.56115e-5   1.0000
group: 2      1.43496e-14  5.4434e-10    2.63615e-5   1.0000
group: 3      1.11987e-14  5.46085e-10   2.05073e-5   1.0000
group: 4      9.82579e-15  5.44772e-10   1.80365e-5   1.0000
group: 5      1.11988e-14  5.43357e-10   2.06104e-5   1.0000
────────────────────────────────────────────────────────────

julia> @time fit!(mind)
  0.394843 seconds (935.71 k allocations: 48.277 MiB, 2.69% gc time)
Linear mixed model fit by maximum likelihood
 y ~ 1 + x + w + z + sex + group + (1 | ID) + (0 + y | ID)
     logLik        -2 logLik          AIC             BIC       
  1.50403153×10⁶ -3.00806306×10⁶ -3.00803906×10⁶  -3.0079249×10⁶

Variance components:
            Column           Variance            Std.Dev.       Corr.
ID       (Intercept)  0.000000245883647524756 0.00049586656222
         y            0.002233402276304851178 0.04725888568624  0.00
Residual              0.000000000000002910355 0.00000005394771
 Number of obs: 100000; levels of grouping factors: 1000

  Fixed-effects parameters:
────────────────────────────────────────────────────────────
                 Estimate    Std.Error      z value  P(>|z|)
────────────────────────────────────────────────────────────
(Intercept)  -1.5368e-5    1.56808e-5   -0.980057     0.3271
x             1.67994e-14  6.22273e-10   2.69968e-5   1.0000
w             2.86739e-14  6.19481e-10   4.62869e-5   1.0000
z             4.10742e-14  6.2029e-10    6.62178e-5   0.9999
sex: m        1.75515e-14  3.84805e-10   4.56115e-5   1.0000
group: 2      1.43496e-14  5.4434e-10    2.63615e-5   1.0000
group: 3      1.11987e-14  5.46085e-10   2.05073e-5   1.0000
group: 4      9.82579e-15  5.44772e-10   1.80365e-5   1.0000
group: 5      1.11988e-14  5.43357e-10   2.06104e-5   1.0000
```
So far, so good. Now let's add in a second RE.

```julia 

julia> @time mnc = zerocorr!(LMM(@formula(y ~ 1 + x + w + z + sex + group + (1 + y| ID) + (1|city)), df), [:ID]);
  0.993234 seconds (1.44 M allocations: 135.859 MiB, 4.72% gc time)

julia> @time mind = LMM(@formula(y ~ 1 + x + w + z + sex + group + (1| ID) + (0+y|ID) + (1|city)), df);
  1.303175 seconds (1.25 M allocations: 147.513 MiB, 18.47% gc time)

julia> @time fit!(mnc) # works
....
julia> @time fit!(mind)
ERROR: DomainError with -110969.0300495916:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).
Stacktrace:
 [1] throw_complex_domainerror(::Symbol, ::Float64) at ./math.jl:31
 [2] sqrt at ./math.jl:493 [inlined]
 [3] map!(::typeof(sqrt), ::Array{Float64,1}, ::Array{Float64,1}) at ./abstractarray.jl:2066
 [4] cholUnblocked!(::LinearAlgebra.Diagonal{Float64,Array{Float64,1}}, ::Type{Val{:L}}) 
 [5] updateL!(::LinearMixedModel{Float64}) 
....
```
Looking at the blocks:

```
julia> describeblocks(mnc)
1,1: UniformBlockDiagonal{Float64} (2000, 2000) UniformBlockDiagonal{Float64}
2,1: SparseArrays.SparseMatrixCSC{Float64,Int32} (30, 2000) BlockedSparse{Float64,1,2}
2,2: LinearAlgebra.Diagonal{Float64,Array{Float64,1}} (30, 30) LinearAlgebra.Diagonal{Float64,Array{Float64,1}}
3,1: Array{Float64,2} (9, 2000) Array{Float64,2}
3,2: Array{Float64,2} (9, 30) Array{Float64,2}
3,3: Array{Float64,2} (9, 9) Array{Float64,2}
4,1: Array{Float64,2} (1, 2000) Array{Float64,2}
4,2: Array{Float64,2} (1, 30) Array{Float64,2}
4,3: Array{Float64,2} (1, 9) Array{Float64,2}
4,4: Array{Float64,2} (1, 1) Array{Float64,2}

julia> describeblocks(mind)
1,1: UniformBlockDiagonal{Float64} (2000, 2000) UniformBlockDiagonal{Float64}
2,1: SparseArrays.SparseMatrixCSC{Float64,Int32} (30, 2000) BlockedSparse{Float64,1,2}
2,2: LinearAlgebra.Diagonal{Float64,Array{Float64,1}} (30, 30) LinearAlgebra.Diagonal{Float64,Array{Float64,1}}
3,1: Array{Float64,2} (9, 2000) Array{Float64,2}
3,2: Array{Float64,2} (9, 30) Array{Float64,2}
3,3: Array{Float64,2} (9, 9) Array{Float64,2}
4,1: Array{Float64,2} (1, 2000) Array{Float64,2}
4,2: Array{Float64,2} (1, 30) Array{Float64,2}
4,3: Array{Float64,2} (1, 9) Array{Float64,2}
4,4: Array{Float64,2} (1, 1) Array{Float64,2}
```
They match in structure which isn't surprising, given the way they're constructed.

The `city` term is the same across models:
```julia
julia> mnc.reterms[2] == mind.reterms[2]
true
```
I'm getting the calculation of `inds` correct:

```julia
julia> mind.reterms[1].inds
2-element Array{Int64,1}:
 1
 4

julia> mnc.reterms[1].inds
2-element Array{Int64,1}:
 1
 4
```

**Comment by dmbates** [comment]
The immediate problem is that `mnc.A[Block(2,1)]` and `mind.A[Block(2,1)]` are different.  It appears that the correct value is the one in `mnc`.  It appears that in `mind` the non-zero values are correct but the indices are wrong.

**Comment by dmbates** [comment]
As I suggested above, the nonzeros in the two sparse matrices `mind.A[Block(2,1)]` and `mnd.A[Block(2,1)]` are the same 
```julia
julia> sort(nonzeros(mind.A[Block(2,1)])) == sort(nonzeros(mnc.A[Block(2,1)]))
true
```
and the column pointers are the same
```julia
julia> mind.A[Block(2,1)].colptr == mnc.A[Block(2,1)].colptr
true
```
so it is the rowvals that have gotten mixed up.
```julia
julia> rowvals(mind.A[Block(2,1)])'
1×2000 Adjoint{Int32,Array{Int32,1}}:
 30  13  17  30  27  11  22  12  24  11  4  24  20  29  2  15  30  9  5  29  12  23  22  1  1  27  20  7  3  26  22  …  12  11  30  4  1  2  6  19  24  5  10  8  14  28  1  26  13  5  3  6  16  11  9  25  26  1  7  10  5  14  26  9
```
```julia
julia> rowvals(mnc.A[Block(2,1)])'
1×2000 Adjoint{Int32,Array{Int32,1}}:
 30  30  13  13  17  17  30  30  27  27  11  11  22  22  12  12  24  24  11  11  4  4  24  24  20  20  29  29  2  2  …  26  13  13  5  5  3  3  6  6  16  16  11  11  9  9  25  25  26  26  1  1  7  7  10  10  5  5  14  14  26  26  9  9
```

File: src/linalg.jl [hunk 1]
```diff
@@ -1,8 +1,15 @@
...
         α=true, β=false) where {T<:BlasFloat}
     BLAS.gemm!('N', 'C', T(α), A, adjB.parent, T(β), C)
 end
 
+function mulαβ!(C::Matrix{T}, A::Matrix{T}, adjB::Diagonal{T,S},
+        α=true, β=false) where {T<:BlasFloat,S}
+    # this could be more efficient for the diagonal case
+    BLAS.gemm!('N', 'C', T(α), A, Matrix(adjB), T(β), C)
+end
+
```
Comment (dmbates) [inline src/linalg.jl]: These methods will no longer be needed after v1.3.0 is released.  All of the `mulαβ!` methods will become `mul!` methods and only the ones that involve matrix types defined in this package will need to be defined.  The version in LinearAlgebra/src/diagonal.jl for julia 1.3.0 is
```julia
@inline mul!(out::AbstractMatrix, in::StridedMatrix, A::Diagonal,
             alpha::Number, beta::Number) =
    out .= (in .* permutedims(A.diag)) .*ₛ alpha .+ out .*ₛ beta
```

File: src/linalg/rankUpdate.jl [hunk 2]
```diff
@@ -86,3 +88,14 @@ function rankUpdate!(C::HermOrSym{T,UniformBlockDiagonal{T}}, A::BlockedSparse{T
...
+function rankUpdate!(C::Diagonal{T, S}, A::Diagonal{T,S}, α=true, β=true) where {T, S}
+    # C := β*C + α*A'A
+
+    length(C.diag) == length(A.diag) ||
+        throw(DimensionMismatch("length(C.diag) ≠ length(A.diag)"))
+
+    for ii in 1:length(C.diag)
+        C.diag[ii] = β * C.diag[ii] + α * A.diag[ii] * A.diag[ii]
+    end
+end
```
Comment (dmbates) [inline src/linalg/rankUpdate.jl]: I think this can be written more concisely as
```julia
function rankUpdate!(C::Diagonal{T,S}, A::Diagonal{T,S}, α::Number=true, β::Number=true) where {T, S}
    C.diag .= β .* C.diag .+ α .* abs2.(A.diag)
    C
end
```

File: src/remat.jl [hunk 3]
```diff
@@ -25,6 +25,57 @@ mutable struct ReMat{T,S} <: AbstractMatrix{T}
...
+
+    inds = sizehint!(Int[], (Snew * (Snew + 1)) >> 1)
+    for j in 1:Snew, i in j:Snew
+        if mask[i,j]
+            push!(inds, m[i,j])
+        end
+    end
+
+    λ = LowerTriangular(Matrix{T}(I, Snew, Snew))
+    adjA =  foldl(vcat, [rr.adjA for rr in reterms])
```
Comment (dmbates) [inline src/remat.jl]: I think this is the problem.  The rows should be interleaved rather than appended.  In your example, the `.adjA` rows from the term `(1|ID)` get mapped to the odd-numbered rows in the result and the `.adjA` rows from the term `(0+y|ID)` get mapped to the even-numbered rows in the result.  I'll see if I can come up with a clean way of doing this.

Comment (dmbates) [reply src/remat.jl]: I think it will be easiest to just generate the `.adjA` for the amalgamated term from the `.z` array and the refs, as is done in the `modelcols(t::RandomEffectsTerm, d::NamedTuple)` method.

Comment (dmbates) [reply src/remat.jl]: We can take some of the code in the `modelcols` method and create a utility
```julia
function adjA(refs::AbstractVector, z::AbstractMatrix)
    S, n = size(z)
    length(refs) == n || throw(DimensionMismatch)
    J = Int32.(1:n)
    II = refs
    if S > 1
        J = repeat(J, inner=S)
        II = Int32.(vec([(r - 1)*S + j for j in 1:S, r in refs]))
    end
    sparse(II, J, vec(z))
end
```
and call it from both the `modelcols` method and the `amalgamate` method.

If this seems okay to you, let me know if you prefer to make the change or have me do it (and possibly tie myself up in a git knot again).

Comment (palday) [reply src/remat.jl]: ah, I should have thought of this myself.

File: src/linalg.jl (hunk 1 above)
Comment (palday) [reply src/linalg.jl]: How do we want to handle the transition to 1.3? Just drop these methods and support for <1.3 ?

**Comment by palday** [comment]
I don't have tests for all the new multiplication methods, but I'm tempted to be lazy on that front if they're all going the way of the dodo in 1.3.

File: src/linalg.jl (hunk 1 above)
Comment (dmbates) [reply src/linalg.jl]: Yes, that would be my preferred approach.

File: src/utilities.jl [hunk 4]
```diff
@@ -11,7 +11,12 @@ the proportion of nonzeros exceeds `threshold`.
 function densify(A::SparseMatrixCSC, threshold::Real = 0.25)
     m, n = size(A)
     if m == n && isdiag(A)  # convert diagonal sparse to Diagonal
-        Diagonal(diag(A))
+        if diag(A) isa SparseVector
+            # sparse diagonals don't make sense
+            Diagonal(Vector(diag(A)))
+        else
+            Diagonal(diag(A))
+        end
```
Comment (dmbates) [inline src/utilities.jl]: Would it be better to write this chunk as
```julia
        Diagonal(Vector(diag(A)))
```
The call to `Vector` should be a no-op if `diag(A)` is already a dense vector.

File: src/linearmixedmodel.jl [hunk 5]
```diff
@@ -65,6 +65,20 @@ function LinearMixedModel(f::FormulaTerm, tbl::Tables.ColumnTable;
...
+        # this reduction step could be expensive for large models
+        reterms_simplified = ReMat{T}[]
+        for gg in grps
+            combined = amalgamate([ret for ret in reterms if fname(ret) == gg])
+            push!(reterms_simplified, combined)
+        end
+        reterms = reterms_simplified
+    end
+
+
```
Comment (dmbates) [inline src/linearmixedmodel.jl]: Let's go ahead and merge the PR like this.  I may end up rewriting this and the _amalgamate function later using the [`BlockDiagonals`](https://github.com/invenia/BlockDiagonals.jl) package later, if that's okay with you.

Comment (palday) [reply src/linearmixedmodel.jl]: Sounds like a good idea.

**Comment by palday** [comment]
Not offensive at all.
