### PR TITLE
Switch to row-major ordering of correlations.

### LINKED ISSUE #218: incorrect zeroing of correlation parameters
The [examples from the docs](https://dmbates.github.io/MixedModels.jl/latest/constructors/#Simplifying-the-random-effect-correlation-structure-1) suggest that the different syntax for removing correlations which should be equivalent are producing different results now when the LHS is categorical:

```julia
julia> fit(MixedModel, @formula(Y ~ 1 + U + (1+U|G)), dat[:sleepstudy], contrasts=Dict(:U=>DummyCoding()))
Linear mixed model fit by maximum likelihood
 Y ~ 1 + U + (1 + U | G)
   logLik   -2 logLik     AIC        BIC    
 -805.39922 1610.79843 1742.79843 1953.53359

Variance components:
            Column     Variance   Std.Dev.    Corr.
G        (Intercept)   955.578308 30.9124297
         U: 1.0        497.183571 22.2976136 -0.30
         U: 2.0        915.645818 30.2596401 -0.57 -0.37
         U: 3.0       1267.226692 35.5981276 -0.31 -0.25 -0.28
         U: 4.0       1484.909119 38.5345185 -0.16 -0.20  0.06  0.75
         U: 5.0       2296.038533 47.9169963  0.72  0.59  0.46  0.30  0.22
         U: 6.0       3850.672299 62.0537855  0.29  0.25  0.87  0.67  0.45  0.48
         U: 7.0       1806.262575 42.5001479  0.47  0.36  0.16  0.91  0.70  0.70  0.50
         U: 8.0       3151.792889 56.1408309  0.56  0.38  0.85  0.77  0.63  0.73  0.59  0.75
         U: 9.0       3075.767360 55.4596011  0.64  0.90  0.78  0.71  0.73  0.38  0.74  0.53  0.85
```

should remove all correlations with intercept:
```julia
julia> fit(MixedModel, @formula(Y ~ 1 + U + (1|G) + (0+U|G)), dat[:sleepstudy], contrasts=Dict(:U=>DummyCoding()))
Linear mixed model fit by maximum likelihood
 Y ~ 1 + U + (1 | G) + (0 + U | G)
   logLik   -2 logLik     AIC        BIC    
 -805.39935 1610.79870 1744.79870 1958.72681

Variance components:
            Column     Variance   Std.Dev.    Corr.
G        (Intercept)   181.213462 13.4615550
         U: 0.0        782.422065 27.9718084   .  
         U: 1.0        863.277684 29.3815875   .     .  
         U: 2.0        627.634941 25.0526434   .     .     .  
         U: 3.0       1231.455404 35.0920989   .     .     .     .  
         U: 4.0       1513.458193 38.9031900  0.69  0.34  0.37  0.36  0.30
         U: 5.0       2335.558526 48.3276166  0.14  0.43  0.26  0.49  0.73  0.71
         U: 6.0       3570.086607 59.7502017  0.60  0.48  0.25  0.42  0.34  0.52  0.87
         U: 7.0       2171.047045 46.5944959  0.65  0.43  0.41  0.55  0.35  0.38  0.91  0.70
         U: 8.0       3225.633405 56.7946600  0.66  0.56  0.57  0.54  0.85  0.74  0.67  0.73  0.70
         U: 9.0       4044.254162 63.5944507  0.73  0.67  0.90  0.83  0.69  0.72  0.43  0.75  0.64  0.88
```

should remove all correlations, but seems to also zero out some of the variance terms (but that could be an estimation thing I guess)
```julia
julia> fit(MixedModel, @formula(Y ~ 1 + U + zerocorr(1+U|G)), dat[:sleepstudy], contrasts=Dict(:U=>DummyCoding()))
Linear mixed model fit by maximum likelihood
 Y ~ 1 + U + MixedModels.ZeroCorr((1 + U | G))
   logLik   -2 logLik     AIC        BIC    
  -882.9138  1765.8276  1807.8276  1874.8797

Variance components:
            Column    Variance   Std.Dev.   Corr.
G        (Intercept)   958.56168 30.960647
         U: 1.0          0.00000  0.000000   .  
         U: 2.0          0.00000  0.000000   .     .  
         U: 3.0          0.00000  0.000000   .     .     .  
         U: 4.0          0.00000  0.000000   .     .     .     .  
         U: 5.0        519.69396 22.796797   .     .     .     .     .  
         U: 6.0       1703.85878 41.277824   .     .     .     .     .     .  
         U: 7.0        608.86850 24.675261   .     .     .     .     .     .     .  
         U: 8.0       1273.10854 35.680647   .     .     .     .     .     .     .     .  
         U: 9.0       1753.94556 41.880133   .     .     .     .     .     .     .     .     .  
```

should be equivalent to the previous (`zerocorr(1 + U| G)`):
```julia
julia> fit(MixedModel, @formula(Y ~ 1 + U + (1|G) + zerocorr(0+U|G)), dat[:sleepstudy], contrasts=Dict(:U=>DummyCoding()))
Linear mixed model fit by maximum likelihood
 Y ~ 1 + U + (1 | G) + MixedModels.ZeroCorr((0 + U | G))
   logLik   -2 logLik     AIC        BIC    
  -878.9844  1757.9688  1801.9688  1872.2139

Variance components:
            Column      Variance      Std.Dev.    Corr.
G        (Intercept)  1134.018890418 33.67519696
         U: 0.0        775.482297289 27.84748278   .  
         U: 1.0        356.726068226 18.88719323   .     .  
         U: 2.0        220.598457629 14.85255728   .     .     .  
         U: 3.0          0.041430896  0.20354581   .     .     .     .  
         U: 4.0         43.482811564  6.59414980   .     .     .     .     .  
         U: 5.0        670.667693798 25.89725263   .     .     .     .     .     .  
         U: 6.0       1740.087547279 41.71435661   .     .     .     .     .     .     .  
         U: 7.0        904.947269466 30.08234149   .     .     .     .     .     .     .     .  
         U: 8.0       1456.355135727 38.16222132   .     .     .     .     .     .     .     .     .  
         U: 9.0       2026.627987970 45.01808512   .     .     .     .     .     .     .     .     .     .  
```

I don't think these are just errors in display since the other parameters appear to be different as well (e.g. the fixed effects SEs).  Maybe these are somehow side effects of this somewhat degenerate example, but they *should* produce the same things so I doubt that's the only thing going on.

### PR DESCRIPTION
**Pull request by dmbates**
Closes #218

I haven't added a test yet.

### CODE REVIEW

File: src/utilities.jl [hunk 1]
```diff
@@ -57,32 +57,25 @@ function normalized_variance_cumsum(A::AbstractMatrix)
...
-Return a tuple of (row,column) tuples in the strict lower triangle of a `k` by `k` matrix.
+const ltriindprs = NTuple{2,Int}[]
 
-The results are memoized in the `strictlowertrid` `Dict` and created by `lowertriinds(k)`
-when needed.
-"""
-indpairs(k) = get!(strictlowertrid, k, lowertriinds(k))
+function checkindprsk(k::Integer)
+    kchoose2 = (k * (k - 1)) >> 1
+    global ltriindprs
```
Comment (palday) [inline src/utilities.jl]: why is this global?

**Comment by palday** [comment]
CIs pass after restarted because of download error.

**Comment by palday** [comment]
Do we need tests for a larger correlation matrix to catch these types of issues?

File: src/utilities.jl (hunk 1 above)
Comment (dmbates) [reply src/utilities.jl]: I found I needed to specify `global` when I was developing the function but that may have been because I was doing it in the REPL.  I'll see what happens if I delete this.  I do want to use the value declared in the module so that it is persistent.

**Comment by dmbates** [comment]
Tests have been added.
